[tool.uv.workspace]
members = ["hindsight", "hindsight-api", "hindsight-dev", "hindsight-mcp-server", "hindsight-openai", "hindsight-langmem", "hindsight-clients/python"]

[tool.uv]
dev-dependencies = []
